### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by rory-vds** [fastmountain/tournament#2]
https://github.com/fastmountain/tournament/blob/2c1297c8e25b2a85beee0ab1ed3274a2e7060e69/src/components/Grid/GridComponent.js#L2

Je import hier lodash zonder dat je het gebruikt. Denk ook na of je zoveel libraries wilt gebruiken.
Ik zie namelijk dat je ook al jQuery gebruikt. Is dat allebei nodig voor zo een kleine app? Wat gebruik je van deze libraries dat niet kan met native JS?

**Comment by fastmountain** [comment]
Uiteraard, ik had eerst nog een test helper aan het project zitten die gebruik maakte van jquery en chai-jquery. Maar ik wilde eerst even focussen op het opzetten voordat ik met de die tests aan de gang ging.
