### ISSUE TITLE
Een hele css framework voor deze app?

### ISSUE THREAD

**Issue by rory-vds** [fastmountain/tournament#6]
https://github.com/fastmountain/tournament/blob/2c1297c8e25b2a85beee0ab1ed3274a2e7060e69/src/static/scss/_alert.scss#L1

Welke scss heb jij zelf geschreven? Je gebruikt hier behoorlijk wat imports.
Een grid gebruiken okay, maar dit is echt alles gebruiken wat bootstrap te bieden heeft.

**Comment by fastmountain** [comment]
Eens, had een enigszins gestripte versie van Bootstrap gebruikt, maar er zat nog flink wat rommel tussen. Alle hulp classes worden niet gebruikt, maar de reset/normalize is handig en de breakpoint mixins zijn heel handig.
